### ISSUE TITLE
Please change 'swift_version' of podspec

### ISSUE THREAD

**Issue by arusu0629** [KyoheiG3/NavigationNotice#10]
Dear @KyoheiG3 
Since [this commit](https://github.com/KyoheiG3/NavigationNotice/commit/03caea807fc5022c03170db481cc23817cff3054) supports swift 5, I'd like you to change the swift_version(4.2 to 5.0) of podspec.

The reason is that every time I do a `pod install`, the version of swift is changed to 4.2

**Comment by KyoheiG3** [comment]
Hi @arusu0629 
Changed swift_version to 5.0 and released 3.1.0.
Thanks.

**Comment by arusu0629** [comment]
Dear @KyoheiG3 
Thank you for quick response!
Confirmed it!!!
